### ISSUE TITLE
Oracle的centos8执行该脚本的系统调优后无法sudo

### ISSUE THREAD

**Issue by xihajim** [jerry048/Tune#4]
Oracle的centos8执行系统调优后无法sudo，报错如下：
sudo: pam_open_session: Permission denied
sudo: policy plugin failed session initialization

包括root用户的crontab也无法正常执行了，报类似的错

**Comment by jerry048** [comment]
https://www.cnblogs.com/dewan/p/16600913.html#:~:text=%E6%94%B6%E8%B5%B7-,sudo%EF%BC%9Apam_open_session%20Permission%20denied,-%E4%B8%80%EF%BC%8C%E9%AA%8C%E8%AF%81%20sudo

可能是以上的问题。试试有没有帮助？
手上没有centos机器

**Comment by xihajim** [comment]
> https://www.cnblogs.com/dewan/p/16600913.html#:~:text=%E6%94%B6%E8%B5%B7-,sudo%EF%BC%9Apam_open_session%20Permission%20denied,-%E4%B8%80%EF%BC%8C%E9%AA%8C%E8%AF%81%20sudo
> 
> 可能是以上的问题。试试有没有帮助？ 手上没有centos机器

对，我也找到估计是这个原因了
脚本中内容如下：
`#File Open Limit
set_file_open_limit_() {
    cat << EOF >>/etc/security/limits.conf
## Hard limit for max opened files
root        hard nofile 1048576
## Soft limit for max opened files
root       soft nofile 1048576
EOF
	return 0
}`


但是脚本中`fs.nr_open=1000000`

导致了nofile 的软硬限制的值超过了内核参数
我一台还保持着root连接，把limits.conf中增加的内容注释掉就OK了
但是另外一台已经退出到普通用户了，再也回不到root也没有sudo权限了，只能之后在控制台重启进单用户修改了，可惜了甲骨文控制台重启后速率就变小了

我另一台debian用了此脚本暂时没有出现这个问题，但根据资料应该也是会有问题的，原因不知

**Comment by jerry048** [comment]
已經修改 感謝幫忙debug 
關於甲骨文這個只能說不好意思了
