### ISSUE TITLE
服务启动失败

### ISSUE THREAD

**Issue by yumaoss** [jerry048/Tune#5]
aws 光帆 Debian12
sudo -s到root，bash <(wget -qO- https://raw.githubusercontent.com/jerry048/Tune/main/tune.sh -b

查看服务状态
bandwidth_limit.service - Bandwidth Limit
Loaded: loaded (/etc/systemd/system/bandwidth_limit.service; enabled; preset: enabled)
Active: activating (auto-restart) (Result: exit-code) since Fri 2024-04-19 06:04:44 UTC; 44ms ago
Process: 2730 ExecStart=/root/.bandwidth_limit.sh (code=exited, status=203/EXEC)
Main PID: 2730 (code=exited, status=203/EXEC)
CPU: 642us
实际.bandwidth_limit.sh文件在/home/admin下

**Comment by jerry048** [comment]
Fixed
